project:
  type: website

website:
  title: "NetworkIsLife"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    #logo: images/ofce_m.png
    search: true
    contents:
      - section: "Network Analysis"
        contents:
        - href: Network_analysis_basics.qmd
        - href: Text_networks.qmd
        - href: CE_network.qmd
      - section: "Intro to Programming"
        contents:
        - href: Intro_programming_basic_operations.qmd
        - href: Intro_programming_DataImportAndPrep.qmd
        - href: Intro_programming_Databasemanip.qmd
        - href: Intro_programming_functions.qmd
        - href: Intro_programming_loops_ifelse.qmd
        - href: Intro_programming_random.qmd
        - href: Intro_programming_visualisation.qmd
      - section: "Text Mining"
        contents:
        - href: feature_extraction.qmd
        - href: Topic_modelling_lda.qmd
        - href: Topic_modelling_bertopic.qmd
        - href: NER.qmd
        - href: Text_networks.qmd


format:
  html:
    theme: Litera
    extra_dependencies: ['amsmath', 'fontawesome5', 'tikz-network', 'xkeyval']
    css: styles.css
    toc: true
    code-fold: true

editor: visual

