project:
  type: website

website:
  title: "NetworkIsLife"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    #logo: images/ofce_m.png
    search: true
    contents:
      - section: "Intro to Programming"
        contents:
        - href: Intro_programming_basic_operations.qmd
          text: "Some basic operations"
      - section: "Import data"
        contents:
        - href: Intro_programming_DataImportAndPrep.qmd
          text: "How to import dat"
      - section: "Feature extraction"
        contents:
        - href: feature_extraction.qmd
          text: "How to extract words of value"
format:
  html:
    theme: Litera
    extra_dependencies: ['amsmath', 'fontawesome5', 'tikz-network', 'xkeyval']
    css: styles.css
    toc: true

editor: visual

