## Random numbers

A random number is a number that is generated unpredictably. These number have various applications in computer science and mathematics. They are used for example in optimisation tasks to help algorithms avoid local optima, they are also used in simulation models to introduce randomness. For example, when we model technological evolution, firms invest in R&D, with a certain probability they will find an innovation, the value of which is defined by a random number. This creates unpredictable outcomes and allows for more interesting (and realistic) analyses.

Even though it's important to be able to introduce this randomness in the analysis of complex systems, we also need to be able to replicate specific scenarios. This is for example the case when the outcome of a model are surprising and we want to analyse more in detail what happens. In this case we need to be able to ensure that running the same model again will provide the same results. This is usually done by something called a **seed**. The seed ensures that the random number functions produce the same value each time.

There are two dimensions that we will look into here.

-   how we can generate these random numbers

-   how we can set a seed

We start by using the **random** package in python, and the **random.seed** function to set the value of the seed. We then use the **.random** function to generate a random value.

```{python}
# import the module
import random
# set the seed
random.seed(21)
# print a randomly generated value
print(random.random())
```

Each time you run this code, you will get the same output.

There are many different random functions that allow for the creation of discrete or continuous values. For example the

```{python}
for i in range(5):
  random_number_1 = random.Random(42).random()
  random_number_2 = random.random()
  print(random_number_1)
  print(random_number_2)


random.seed(42)
for i in range(5):
    random.seed(42)
    random_number_1 = random.random()
    print(random_number_1)
```

```{python}
import random
random.random()
random.randint(0, 5)
random.randrange(0, 10)
```

For a mode complete view on random number with python see [here](https://www.w3schools.com/python/module_random.asp).
