<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Johannes VAN DER POL">

<title>NetworkIsLife – Collaboration Networks</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles2.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="././imgs/logo5.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">NetworkIsLife</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./package.html"> 
<span class="menu-text">R Package</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./network.html" aria-current="page"> 
<span class="menu-text">Network Theory</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./dafs-dst.html"> 
<span class="menu-text">Data Science Track</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./dafs-esm.html"> 
<span class="menu-text">ESM Track</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Network_manual_chap_collaborations.html">Collaboration Networks</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./network.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Analysis for Decision-Making</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Network_analysis_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The basics of Network Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Text_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textual Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Network_manual_chap_citations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Citation Network Analysis for Decision-Making</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Network_manual_chap_collaborations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Collaboration Networks</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#collaborations" id="toc-collaborations" class="nav-link active" data-scroll-target="#collaborations">Collaborations</a>
  <ul class="collapse">
  <li><a href="#analyzing-a-collaboration-network" id="toc-analyzing-a-collaboration-network" class="nav-link" data-scroll-target="#analyzing-a-collaboration-network">Analyzing a Collaboration Network</a></li>
  <li><a href="#data-and-network-construction" id="toc-data-and-network-construction" class="nav-link" data-scroll-target="#data-and-network-construction">Data and Network Construction</a></li>
  <li><a href="#on-combining-sources" id="toc-on-combining-sources" class="nav-link" data-scroll-target="#on-combining-sources">On Combining Sources</a></li>
  <li><a href="#comparison-with-the-funded-network" id="toc-comparison-with-the-funded-network" class="nav-link" data-scroll-target="#comparison-with-the-funded-network">Comparison with the Funded Network</a></li>
  <li><a href="#analyzing-a-co-author-network" id="toc-analyzing-a-co-author-network" class="nav-link" data-scroll-target="#analyzing-a-co-author-network">Analyzing a Co-Author Network</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Collaboration Networks</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Johannes VAN DER POL </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="collaborations" class="level2">
<h2 class="anchored" data-anchor-id="collaborations">Collaborations</h2>
<p>In strategic technological intelligence, collaboration is a high-value information signal. A technological collaboration implies pooling technical capabilities, which are at the core of firms’ competitive advantage. Observing two actors combining capabilities is therefore a strong signal of technological need.</p>
<p>Collaboration among innovative firms has intensified over several decades <span class="citation" data-cites="Duysters00">(<a href="#ref-Duysters00" role="doc-biblioref">Duysters and Hagedoorn 2000</a>)</span>. As technologies become more complex, it is increasingly difficult for one actor to master all required techniques and technologies. As a result, actors build links with others, sometimes even competitors, in order to innovate <span class="citation" data-cites="hagedoorn1996choosing narula1999innovating">(<a href="#ref-hagedoorn1996choosing" role="doc-biblioref">Hagedoorn and Narula 1996</a>; <a href="#ref-narula1999innovating" role="doc-biblioref">Narula and Hagedoorn 1999</a>)</span>. Collaboration has been identified as beneficial for firms <span class="citation" data-cites="mcevily2005embedded">(<a href="#ref-mcevily2005embedded" role="doc-biblioref">McEvily and Marcus 2005</a>)</span>, innovation <span class="citation" data-cites="kogut1992knowledge">(<a href="#ref-kogut1992knowledge" role="doc-biblioref">Kogut and Zander 1992</a>)</span>, and growth/survival <span class="citation" data-cites="mcevily2005embedded watson2007modeling">(<a href="#ref-mcevily2005embedded" role="doc-biblioref">McEvily and Marcus 2005</a>; <a href="#ref-watson2007modeling" role="doc-biblioref">Watson 2007</a>)</span>.</p>
<p>The discussion above concerns mainly technological collaboration, where each firm contributes technical input. But collaboration can also be financially motivated. A firm with technical capability but insufficient funds may partner with another actor to finance research. In some data sources, distinguishing motivation is difficult. For example, in patents, having two assignees does not imply equal technological contribution; one actor may be listed due to financial participation. The distinction is clearer in funded research projects where the funder is explicitly identified and participants are expected to provide technological contributions (ANR and European projects).</p>
<p>In a knowledge economy, a firm’s key asset is the knowledge it controls and mobilizes for market positioning <span class="citation" data-cites="penrose1959theory">(<a href="#ref-penrose1959theory" role="doc-biblioref">Penrose 1959</a>)</span>. From a Knowledge-Based View, collaboration is risky because it opens access to strategically valuable knowledge <span class="citation" data-cites="penrose1959theory">(<a href="#ref-penrose1959theory" role="doc-biblioref">Penrose 1959</a>)</span>. In that sense, collaboration is a strong indicator of real technological need when alternatives are limited.</p>
<p>When competing firms collaborate and even share intellectual property, this typically indicates that both actors could not obtain the required capability through easier alternatives. In this chapter, collaboration is analyzed mainly through a knowledge-flow lens. These flows may include non-strategic information (tool recommendations, organizational practices, managerial insights) as well as core technical knowledge. They can diffuse from collaborator to collaborator and propagate through the network.</p>
<p>This propagation can be beneficial in two ways:</p>
<ul>
<li>Better information can improve innovation across the network and ultimately benefit users.</li>
<li>Incoming new ideas improve an actor’s own inventive potential.</li>
</ul>
<p>An actor that is too closed may face low diversity of ideas, reducing creativity. Repeated collaboration can increase productivity because actors work better together over time, but it can also reduce creativity.</p>
<p>These dynamics are visible in network representations. Strategically, they reveal how actors organize external technological sourcing.</p>
<p>As with any network, we follow a three-step analysis, with a clear objective at each level.</p>
<div id="fig-collab-tableau-enjeux" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-tableau-enjeux-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Collab/General/Collab_tableau_enjeux.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-tableau-enjeux-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Summary table of information extracted from collaboration networks by analysis level (macro, meso, micro).
</figcaption>
</figure>
</div>
<p>For more detail on collaboration effects, see <span class="citation" data-cites="vanderpol_thesis">Van Der Pol (<a href="#ref-vanderpol_thesis" role="doc-biblioref">2016</a>)</span>.</p>
<section id="analyzing-a-collaboration-network" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-a-collaboration-network">Analyzing a Collaboration Network</h3>
<p>This section addresses collaboration networks between actors. Such networks can be built from multiple data sources, so we first discuss source-specific biases and limits.</p>
</section>
<section id="data-and-network-construction" class="level3">
<h3 class="anchored" data-anchor-id="data-and-network-construction">Data and Network Construction</h3>
<p>This subsection explains which information is used to generate collaboration networks from different data sources, and highlights limits and complementary signals relevant for analysis.</p>
<section id="patents" class="level4">
<h4 class="anchored" data-anchor-id="patents">Patents</h4>
<p>Patent data sources are numerous and differ widely in coverage and cleaning quality. Patent office data are generally available for free, but often do not fully reflect ownership changes tracked in specialized databases. Commercial sources (e.g., Questel Orbit, Orbis-IP) aggregate multiple offices and resolve many issues related to firm name changes and parent-subsidiary structures. Lower-cost alternatives such as PATSTAT exist but require more manual affiliation cleaning. Free sources such as Google Patents can also be useful.</p>
<p>In what follows, we stay close to primary sources (office PDFs, Espacenet, Google Patents) to avoid provider-specific adjustments. The key point is to be aware of potential biases and verify them explicitly.</p>
<p>In the simplest form, a collaboration edge is created when two or more actors appear on the same patent document as assignees.</p>
<div id="fig-collab-brevets-exemplesimple" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-brevets-exemplesimple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Collab/Brevets/collab_brevets_exemplesimple.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-brevets-exemplesimple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Example of collaboration extraction from patent assignees (field 73). If two or more assignees are listed, create nodes and edges; filing year can be used as temporal information.
</figcaption>
</figure>
</div>
<p>Patent analysis is often done at the family level (all unitary documents covering one invention). This may create issues when assignees differ across documents within the same family.</p>
<div id="fig-collab-brevets-exemplefamille" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-brevets-exemplefamille-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Collab/Brevets/collab_brevets_exemplefamille.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-brevets-exemplefamille-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Two patent documents from the same family with different assignees. Herakles and Airbus Safran Launchers reflect a name change; without cleaning, both appear as distinct nodes.
</figcaption>
</figure>
</div>
<p>The most critical case is patent transfer. A single document in a family may be sold, making the buyer appear as a family assignee without any original collaboration.</p>
<div id="fig-collab-brevets-exemplerachat" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-brevets-exemplerachat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Collab/Brevets/collab_brevets_exemplerachat.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-brevets-exemplerachat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Partial assignee transfer case: Google acquired Mosaid, which had acquired North American patents from Pirelli. Family-level data can falsely look like co-assignment collaboration.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>A patent co-assignment link is interpreted as pooling technical capabilities and implies knowledge flow. Because it includes shared intellectual property, it is generally a strong tie.</p>
</div>
</div>
</section>
<section id="scientific-publications" class="level4">
<h4 class="anchored" data-anchor-id="scientific-publications">Scientific Publications</h4>
<p>Scientific outputs are also widely used for collaboration analysis. Here the key entities are author affiliations, not the authors themselves (co-author networks are treated later).</p>
<p>Publication data are often behind paywalls (Scopus, Web of Science), but free sources exist with different coverage (e.g., ScanR, HAL-linked records, arXiv preprints). Commercial providers usually offer cleaner affiliation matching.</p>
<div id="fig-collab-publi-scopus" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-publi-scopus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Collab/Publis/Collab_publi_scopus.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-publi-scopus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Affiliations used to build collaboration networks from scientific publications.
</figcaption>
</figure>
</div>
<p>As with patents, we can add publication date to collaboration edges. However, collaboration necessarily predates publication because research and publication take time. Compared with patents, affiliations (especially universities/research institutes) are often more stable.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>A publication collaboration tie is usually weaker than patent co-assignment because it does not involve direct IP ownership. It still indicates shared work and knowledge flow.</p>
</div>
</div>
</section>
<section id="european-projects" class="level4">
<h4 class="anchored" data-anchor-id="european-projects">European Projects</h4>
<p>A European project is research funded fully or partly by the European Commission, usually in response to calls aligned with EU priorities (e.g., links with China, technological standardization).</p>
<p>These projects generally include diverse actors (multinationals, SMEs, startups, universities, research institutes). Although all participants contribute, they are not necessarily in direct bilateral contact. Knowledge flow should therefore not be over-interpreted as universal across all pairs.</p>
<p>Data are available through the European Commission (CORDIS). Raw files provide detailed project-level information (partners, dates, funding amounts, country), but no full affiliation cleaning.</p>
<p>Unlike patents and publications (outputs), European projects are research inputs and should be interpreted accordingly.</p>
<div id="fig-collab-cordis" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-cordis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Collab/Cordis/collab_cordis.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-cordis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Example project page from CORDIS. Projects include roles such as coordinator and participants; role metadata can be carried into the network.
</figcaption>
</figure>
</div>
<p>Project start and end dates are available and provide clearer temporal anchors than publication/patent dates.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>A project tie indicates shared contribution to a project objective. It does not necessarily imply strong direct knowledge flow between all participant pairs. Complementary publication evidence is useful to refine interpretation.</p>
</div>
</div>
</section>
<section id="anr-projects" class="level4">
<h4 class="anchored" data-anchor-id="anr-projects">ANR Projects</h4>
<p>ANR-funded projects are similar to EU projects in structure. Data are available on ANR project pages and as CSV/XLSX files (e.g., via data.gouv.fr), including coordinator, partners, project start date, duration, and additional fields such as abstracts.</p>
<div id="fig-collab-anr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-anr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Collab/ANR/collab_ANR.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-anr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Information available for ANR-funded projects.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>ANR project ties should be interpreted with the same caution as EU project ties: they indicate knowledge combination potential and possible knowledge flow, not guaranteed direct bilateral transfer.</p>
</div>
</div>
</section>
</section>
<section id="on-combining-sources" class="level3">
<h3 class="anchored" data-anchor-id="on-combining-sources">On Combining Sources</h3>
<p>Given multiple sources, it is tempting to build one global collaboration network. But combining sources implicitly treats all links as equivalent (patent, EU project, publication, ANR), which creates interpretation issues.</p>
<p>Main risks:</p>
<ul>
<li>One project can produce multiple publications, inflating edge weights if each source event is counted independently.</li>
<li>Patent co-assignment is less frequent than publication/project collaboration; its stronger, rarer ties may be diluted in denser mixed-source networks.</li>
<li>The key interpretation problem is semantic: what does the combined network actually represent? Mixed networks are useful to map an ecosystem visually, but network indicators become harder to interpret unless source-specific analyses are run in parallel.</li>
</ul>
<p>For an example combining scientific publications and patents, see <span class="citation" data-cites="van2018co">Pol and Rameshkoumar (<a href="#ref-van2018co" role="doc-biblioref">2018</a>)</span>.</p>
<section id="analyzing-a-collaboration-ecosystem" class="level4">
<h4 class="anchored" data-anchor-id="analyzing-a-collaboration-ecosystem">Analyzing a Collaboration Ecosystem</h4>
<p>To understand innovation emergence in a domain, collaboration network analysis is essential. It helps identify actors open to collaboration, communities with repeated collaboration patterns, and each actor’s local ecosystem. Combined with a standard domain analysis, this informs external technological sourcing strategies.</p>
<p>Here we analyze 5G collaboration networks from Scopus affiliations. We compare:</p>
<ul>
<li>Publications with funding acknowledgment.</li>
<li>Publications without funding acknowledgment.</li>
</ul>
<p>Scopus identifies funding either from author declarations or acknowledgment text. The dataset includes 22,532 scientific documents between 2010 and 2021: 7,435 with funding and 13,107 without.</p>
<section id="macro-analysis-of-the-collaboration-network" class="level5">
<h5 class="anchored" data-anchor-id="macro-analysis-of-the-collaboration-network">Macro Analysis of the Collaboration Network</h5>
<p>Figure <a href="#fig-collab-5g-non-funded" class="quarto-xref">Figure&nbsp;8</a> shows the affiliation collaboration network built from non-funded publications only. An edge indicates at least two distinct co-publications (edge weight &gt;= 2).</p>
<div id="fig-collab-5g-non-funded" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-5g-non-funded-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Publis/Collab_5G_publis_non_fi_color_community.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-5g-non-funded-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Collaboration network from non-funded scientific publications. Node size represents number of collaborators; node color represents Louvain community.
</figcaption>
</figure>
</div>
<p>The network has a single connected component (no isolated collaboration clusters). It contains 526 actors and 1,185 collaboration links, with mean degree 2.25. Density is low (0.009) and clustering is high (0.44), indicating clear community structure. Modularity (0.697) identifies 8 communities.</p>
<p>No single actor structures the whole network; instead, central actors are mostly central within their own communities. The global structure is driven by interconnection of well-defined communities rather than a strict hierarchical architecture.</p>
</section>
<section id="meso-analysis" class="level5">
<h5 class="anchored" data-anchor-id="meso-analysis">Meso Analysis</h5>
<p>Communities identified at macro level suggest a geographic logic. To test this, nodes are colored by country in Figure <a href="#fig-collab-5g-country" class="quarto-xref">Figure&nbsp;9</a>.</p>
<div id="fig-collab-5g-country" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-5g-country-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Publis/Collab_5G_publi_color_country_with_JP.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-5g-country-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Collaboration network from non-funded publications, colored by country.
</figcaption>
</figure>
</div>
<p>Nationally structured communities become more explicit. Industrial actors often act as gatekeepers between national research communities. A salient case is the Japanese cluster, weakly connected to the rest of the network, with private actors (e.g., NEC, Fujitsu) bridging to external communities.</p>
<p>Universities are central within national communities, while large industrial actors are more central at the global network level (e.g., Huawei, Ericsson, Nokia, IBM, Intel).</p>
<p>The French community is relatively inward-looking, with links to the wider network primarily mediated by industrial actors (Orange Labs, Thales, Montimage) plus Grenoble. The Japanese community is also relatively peripheral, while the US community is more distributed and the Chinese community is structured around major universities strongly connected internationally.</p>
</section>
<section id="micro-analysis-of-the-french-collaboration-subnetwork" class="level5">
<h5 class="anchored" data-anchor-id="micro-analysis-of-the-french-collaboration-subnetwork">Micro Analysis of the French Collaboration Subnetwork</h5>
<p>Figure <a href="#fig-collab-5g-fr" class="quarto-xref">Figure&nbsp;10</a> shows links involving at least one French actor.</p>
<div id="fig-collab-5g-fr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-5g-fr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Publis/Collab_5G_publi_FR.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-5g-fr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: French 5G collaboration subnetwork (all links with at least one French actor).
</figcaption>
</figure>
</div>
<p>CNRS is highly central and connected to many universities. Major structuring actors include Rennes, Grenoble, and INRIA. Industrial actors (e.g., Thales, Orange; and at European scale Nokia, STMicroelectronics) are present but often less interconnected with each other than with universities.</p>
<p>Each industrial actor tends to have its own local collaboration ecosystem around specific academic partners. Huawei appears in a more peripheral position through links with Rennes and Thales. US actors are largely absent from this French subnetwork.</p>
</section>
</section>
</section>
<section id="comparison-with-the-funded-network" class="level3">
<h3 class="anchored" data-anchor-id="comparison-with-the-funded-network">Comparison with the Funded Network</h3>
<p>We now compare the non-funded network with the funded network (multi-affiliation publications with explicit funding acknowledgment).</p>
<div id="fig-collab-5g-funded" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collab-5g-funded-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Publis/Collab_5G_publi_color_country_financee.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collab-5g-funded-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Funded collaboration network with the same country color code as the non-funded network.
</figcaption>
</figure>
</div>
<p>Visual comparison suggests both networks have one giant component. The funded network appears denser, with the French community closer to the broader European cluster. The Japanese community is less visible. To validate visual interpretation, we use summary statistics.</p>
<p>Table <a href="#tbl-network-comparison" class="quarto-xref">Table&nbsp;1</a> compares funded, non-funded, and combined networks.</p>
<div id="tbl-network-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-network-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Network statistics comparison between funded, non-funded, and combined collaboration networks.
</figcaption>
<div aria-describedby="tbl-network-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Funded Network</th>
<th style="text-align: right;">Non-Funded Network</th>
<th style="text-align: right;">Combined</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actors</td>
<td style="text-align: right;">587</td>
<td style="text-align: right;">526</td>
<td style="text-align: right;">755</td>
</tr>
<tr class="even">
<td>Links</td>
<td style="text-align: right;">1731</td>
<td style="text-align: right;">1185</td>
<td style="text-align: right;">2494</td>
</tr>
<tr class="odd">
<td>Density</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="even">
<td>Centralization</td>
<td style="text-align: right;">0.0045</td>
<td style="text-align: right;">0.0055</td>
<td style="text-align: right;">0.0033</td>
</tr>
<tr class="odd">
<td>Clustering</td>
<td style="text-align: right;">0.511</td>
<td style="text-align: right;">0.440</td>
<td style="text-align: right;">0.470</td>
</tr>
<tr class="even">
<td>Triangles</td>
<td style="text-align: right;">1919</td>
<td style="text-align: right;">716</td>
<td style="text-align: right;">2903</td>
</tr>
<tr class="odd">
<td>Diameter</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td>Average path length</td>
<td style="text-align: right;">3.64</td>
<td style="text-align: right;">3.886</td>
<td style="text-align: right;">3.49</td>
</tr>
<tr class="odd">
<td>Mean degree</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">6.6</td>
</tr>
<tr class="even">
<td>TPT</td>
<td style="text-align: right;">3.269</td>
<td style="text-align: right;">1.361</td>
<td style="text-align: right;">3.845</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The funded network includes 61 more actors and 546 more links than the non-funded network, indicating both entry of new actors and additional collaboration among existing actors. Higher clustering and triangle counts indicate stronger local densification in funded collaborations.</p>
<p>The combined network (funded + non-funded) has 755 actors and 2,494 links, with stronger overall connectivity.</p>
<p>The original LaTeX chapter references an additional figure (<code>5G_scopus_players_added_through_financing</code>) stored outside this workspace. That file is not available in the current project, so it is not embedded here.</p>
<p>A set of examples of actors appearing only in one network is shown below (as in the source chapter):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Actors Exclusive to Non-Funded Network</th>
<th>Actors Exclusive to Funded Network</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AIRBUS EP</td>
<td>ECOLE NORMALE SUPERIEURE PARIS</td>
</tr>
<tr class="even">
<td>CEMEF FR</td>
<td>INST MINES TELECOM FR</td>
</tr>
<tr class="odd">
<td>DISPOSABLE LAB</td>
<td>ISEP FRANCE</td>
</tr>
<tr class="even">
<td>LRI UNIV PARIS SUD FR</td>
<td>ITER</td>
</tr>
<tr class="odd">
<td>METEOR NETWORK</td>
<td>OMMIC S A S BREVANNES FRANCE</td>
</tr>
<tr class="even">
<td>TECHNOLOGICAL RES INST SYSTEMX</td>
<td>TELECOM RES DEVELOPMENT LANNION</td>
</tr>
<tr class="odd">
<td>UNIVs FRANCHE COMTE</td>
<td>VIRTUAL OPEN SYSTEMS FRANCE</td>
</tr>
<tr class="even">
<td>UNIVs AIX MARSEILLE</td>
<td>WHEN AB PARIS FRANCE</td>
</tr>
<tr class="odd">
<td>UNIVs LYON FR</td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="analyzing-a-co-author-network" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-a-co-author-network">Analyzing a Co-Author Network</h3>
<p>Co-author network analysis can answer strategic questions such as:</p>
<ul>
<li>Which researchers are leading figures in a field?</li>
<li>Which researchers are most influential within a focal organization?</li>
<li>What are the internal research teams?</li>
<li>What research themes are emerging?</li>
<li>How is R&amp;D organized within an actor?</li>
</ul>
<p>We illustrate this with one research laboratory and one firm case.</p>
<section id="researcher-network" class="level4">
<h4 class="anchored" data-anchor-id="researcher-network">Researcher Network</h4>
<p>This example uses scientific outputs (journal papers, books, conference communications, posters, etc.) to:</p>
<ul>
<li>Map the research ecosystem (external collaborators of laboratory researchers).</li>
<li>Identify internal researchers who provide access to external actors.</li>
<li>Identify internal collaboration patterns.</li>
<li>Identify research teams.</li>
</ul>
<p>We first focus on internal links only (researchers from the same lab), using five years of outputs and filtering to intra-lab co-authorship ties.</p>
<div id="fig-bse-internal" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bse-internal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Publis/BSE_nw_publis_5ans_interne_anonyme2.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bse-internal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Internal co-publication network of researchers in a research laboratory. Node size = degree; node color = Louvain community; edge thickness = collaboration frequency.
</figcaption>
</figure>
</div>
<p>The network has four connected components. Secondary components indicate groups collaborating internally without connecting to the rest of the lab network. Reasons can vary (topic specialization, recent project-based collaboration, local organizational effects).</p>
<p>The giant component itself is community-structured, connected through bridge researchers (gatekeepers). These bridging roles are important for laboratory cohesion and cross-community information flow.</p>
<p>Some actors are central inside a community but do not bridge communities, reflecting specialization. Edge thickness also reveals strong dyads/triads with repeated collaboration intensity.</p>
<p>For lab management, both types of actors matter:</p>
<ul>
<li>Community cores (theme leaders) for thematic steering.</li>
<li>Bridge actors for cross-team cohesion and information circulation.</li>
</ul>
<p>Internal collaboration is only part of the picture. External openness also matters.</p>
<div id="fig-reseau-collab-gretha" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reseau-collab-gretha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Publis/Reseau_collab_gretha.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reseau-collab-gretha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Full co-authorship network for the laboratory over its whole period. Blue nodes represent internal researchers; other nodes are external collaborators.
</figcaption>
</figure>
</div>
<p>This full network shows a dense internal core plus more externally oriented researchers at the periphery. Some “ball-like” clusters represent single publications with many co-authors.</p>
<p>To inspect temporal dynamics, edges can be colored by recency:</p>
<div id="fig-bse-date" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bse-date-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Publis/BSE_nw_publis_couleur_par_date.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bse-date-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Laboratory co-authorship network with recent links (&lt;= 5 years) in blue and older links (&gt; 5 years) in red.
</figcaption>
</figure>
</div>
<p>This highlights that many observed links are relatively old. That does not imply collaboration has ended, but it helps distinguish stable legacy ties from recently active ones.</p>
<p>A methodological caveat remains: publications with very large author lists often imply weaker average pairwise collaboration intensity.</p>
</section>
<section id="solvay-inventor-network" class="level4">
<h4 class="anchored" data-anchor-id="solvay-inventor-network">Solvay Inventor Network</h4>
<p>Inventor identity is mandatory in patent filing, making inventors a rich signal for analyzing firm R&amp;D activity through networks. Inventor networks reveal teams working on specific themes, allowing estimation of effort allocation by topic and detection of cross-theme mobility when specialized inventors begin co-inventing with other technical communities.</p>
<p>This case uses Solvay patents from Questel Orbit, 1996 to present, totaling 3,396 patent families. Over this period, Solvay acquired Rhodia and Cytec; inventor-network structure is expected to reflect these integrations.</p>
<div id="fig-solvay-inventors-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-solvay-inventors-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Brevets/solvay_brevets_collab_inventeurs2.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-solvay-inventors-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Solvay inventor collaboration network. Node = inventor; edge = at least one shared patent; node color = modularity community.
</figcaption>
</figure>
</div>
<div id="fig-solvay-inventors-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-solvay-inventors-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Brevets/solvay_brevets_collab_inventeurs_dyn2.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-solvay-inventors-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Solvay inventor network with temporal activity overlay. Red nodes: no co-filing since 2015; green nodes: at least one filing since 2016; node size = centrality.
</figcaption>
</figure>
</div>
<div id="fig-solvay-inventors-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-solvay-inventors-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="images/Collab/Brevets/solvay_brevets_collab_inventeurs3.pdf" class="img-fluid quarto-figure quarto-figure-center" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-solvay-inventors-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Alternative Solvay inventor view with the same encoding of activity and centrality.
</figcaption>
</figure>
</div>



</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Duysters00" class="csl-entry" role="listitem">
Duysters, Geert, and John Hagedoorn. 2000. <span>“Organizational Modes of Strategic Technology Partnering.”</span> <em>Journal of Scientifi &amp; Industrial Research</em> 59: 640–49.
</div>
<div id="ref-hagedoorn1996choosing" class="csl-entry" role="listitem">
Hagedoorn, J., and R. Narula. 1996. <span>“Choosing Organizational Modes of Strategic Technology Partnering: International and Sectoral Differences.”</span> <em>Journal of International Business Studies</em> 27 (2): 265–84.
</div>
<div id="ref-kogut1992knowledge" class="csl-entry" role="listitem">
Kogut, Bruce, and Udo Zander. 1992. <span>“Knowledge of the Firm, Combinative Capabilities, and the Replication of Technology.”</span> <em>Organization Science</em> 3 (3): 383–97.
</div>
<div id="ref-mcevily2005embedded" class="csl-entry" role="listitem">
McEvily, B., and A. Marcus. 2005. <span>“Embedded Ties and the Acquisition of Competitive Capabilities.”</span> <em>Strategic Management Journal</em> 26 (11): 1033–55.
</div>
<div id="ref-narula1999innovating" class="csl-entry" role="listitem">
Narula, Rajneesh, and John Hagedoorn. 1999. <span>“Innovating Through Strategic Alliances: Moving Towards International Partnerships and Contractual Agreements.”</span> <em>Technovation</em> 19 (5): 283–94.
</div>
<div id="ref-penrose1959theory" class="csl-entry" role="listitem">
Penrose, Edith T. 1959. <span>“The Theory of the Growth of the Firm, 1959.”</span> <em>Cambridge, MA</em>.
</div>
<div id="ref-van2018co" class="csl-entry" role="listitem">
Pol, Johannes van der, and Jean-Paul Rameshkoumar. 2018. <span>“The Co-Evolution of Knowledge and Collaboration Networks: The Role of the Technology Life-Cycle.”</span> <em>Scientometrics</em> 114 (1): 307–23.
</div>
<div id="ref-vanderpol_thesis" class="csl-entry" role="listitem">
Van Der Pol, Johannes. 2016. <span>“<span class="nocase">Social network of firms, innovation and industrial performance</span>.”</span> Theses, <span>Universit<span>é</span> de Bordeaux</span>. <a href="https://tel.archives-ouvertes.fr/tel-01532053">https://tel.archives-ouvertes.fr/tel-01532053</a>.
</div>
<div id="ref-watson2007modeling" class="csl-entry" role="listitem">
Watson, J. 2007. <span>“Modeling the Relationship Between Networking and Firm Performance.”</span> <em>Journal of Business Venturing</em> 22 (6): 852–74.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/JPvdP\.github\.io\/NetworkIsLife\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>